site_name: "DRF API Client"
site_description: "A Kotlin Multiplatform library for working with the unofficial Drop Research Facilities (DRF) API."
site_author: "GW2ToolBelt"
site_url: "https://gw2toolbelt.github.io/drf-api-client"
copyright: Copyright &copy; 2021 - 2024 Leon Linhart

repo_name: "GW2ChatLinks"
repo_url: "https://github.com/GW2ToolBelt/drf-api-client"
remote_branch: "gh-pages"
docs_dir: "docs/site"
site_dir: "build/site"

theme:
  name: "material"
  icon:
    logo: material/hammer-wrench
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: "Roboto"
    code: "JetBrains Mono"
  features:
    - navigation.footer
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tracking
    - toc.integrate

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - footnotes
  - toc:
      permalink: true
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - 'Overview': index.md
  - 'License': license.md
  - 'API Reference': api/index.html

plugins:
  - mike
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: 'https://github.com/GW2ToolBelt'
  version:
    provider: mike